=== vlabatut/totalboumboum/trunk/TBB/resources/schemas/Archive.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="_TournamentTypes.xsd"/>

	<xsd:complexType name="tTournament">
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="type" type="tTournamentType" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tPlayed">
		<xsd:attribute name="matches" type="xsd:integer" use="required" />
		<xsd:attribute name="rounds" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tDates">
		<xsd:attribute name="start" type="xsd:dateTime" use="required" />
		<xsd:attribute name="save" type="xsd:dateTime" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tPlayers">
		<xsd:sequence>
			<xsd:element name="player" type="tPlayer" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tPlayer">
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tArchive">
		<xsd:sequence>
			<xsd:element name="tournament" type="tTournament" />
			<xsd:element name="played" type="tPlayed" />
			<xsd:element name="dates" type="tDates" />
			<xsd:element name="players" type="tPlayers" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="archive" type="tArchive" />

</xsd:schema>

=== vlabatut/totalboumboum/TBB/resources/saves/default_backup/archive.xml
<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\resources\schemas\archive.xsd">
	<tournament name="Tournament-séquence court" type="sequence" />
	<played matches="1" rounds="4" />
	<dates start="2009-02-09T21:37:26" save="2009-02-09T21:46:52" />
	<players>
		<player name="0809v2.Altay+Basaranoğlu" />
		<player name="0809v2.Erişik+Pektaş" />
		<player name="0809v2.Günalp+Yürtsever" />
		<player name="Joueur humain" />
	</players>
</archive>

=== vlabatut/totalboumboum/trunk/TBB/resources/saves/Gsu201011Cup/archive.xml
<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\resources\schemas\archive.xsd">
	<!--
	Total Boum Boum
	Copyright 2008-2014 Vincent Labatut
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see http://www.gnu.org/licenses.
-->
	<tournament name="Tournoi de Galatasaray IV" type="CUP" />
	<played matches="0" rounds="0" />
	<dates start="2013-01-14T21:01:02" save="2013-01-14T21:01:13" />
	<players>
		<player name="1011.Kesimal+Varol" />
		<player name="1011.Göçmenoğlu+Hekimoğlu" />
		<player name="1011.Çalışkan+Seven" />
		<player name="1011.Akbulut+Küpelioğlu" />
		<player name="1011.Hacıbektaşoğlu+İlgar" />
		<player name="1011.Büyüktopaç+Turak" />
		<player name="1011.İsbir+Koyaş" />
		<player name="1011.Özdöker+Özen" />
	</players>
</archive>
