=== vlabatut/totalboumboum/trunk/TBB/resources/schemas/Colormap.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="tValue">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="255" />		
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="tColor">
		<xsd:attribute name="index" type="xsd:integer" use="required" />
		<xsd:attribute name="red" type="tValue" use="required" />
		<xsd:attribute name="green" type="tValue" use="required" />
		<xsd:attribute name="blue" type="tValue" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tColormap">
		<xsd:sequence>
			<xsd:element name="color" type="tColor" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="colormap" type="tColormap" />

</xsd:schema>

=== vlabatut/totalboumboum/TBB/resources/instances/superbomberman1/bombs/penetration/animes/colormaps/rust.xml
<?xml version="1.0" encoding="utf-8"?>
<colormap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../schemas/colormap.xsd" >		
<!-- 
	Total Boum Boum
	Copyright 2008-2013 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
	
	<color index="00" red="137" green="054" blue="018" /> <!-- contours -->
	<color index="01" red="145" green="069" blue="021" /> <!-- corps très foncé -->
	<color index="02" red="136" green="075" blue="010" /> <!-- corps foncé -->
	<color index="03" red="187" green="118" blue="043" /> <!-- corps clair -->
	<color index="04" red="158" green="087" blue="011" /> <!-- corps normal -->
	<color index="05" red="218" green="154" blue="085" /> <!-- corps très clair -->
	<color index="09" red="255" green="207" blue="155" /> <!-- corps très très clair -->
	<color index="14" red="255" green="255" blue="255" /> <!-- reflets (blanc cassé) -->

</colormap>
