=== vlabatut/totalboumboum/TBB/resources/schemas/animes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="_direction.xsd"/>
<xsd:include schemaLocation="_colors.xsd"/>
<xsd:include schemaLocation="_gesture_name.xsd"/>

<!-- 
	Total Boum Boum
	Copyright 2008-2012 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
-->

	<xsd:simpleType name="tBasePosition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="down" />
			<xsd:enumeration value="boundHeight" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="tAbstractImage">
		<xsd:attribute name="xShift" type="xsd:double" use="optional" />
		<xsd:attribute name="yShift" type="xsd:double" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tImageFile">
		<xsd:complexContent>
			<xsd:extension base="tAbstractImage">
				<xsd:attribute name="file" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tImageRef">
		<xsd:complexContent>
			<xsd:extension base="tAbstractImage">
				<xsd:attribute name="name" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:group name="gImage">
		<xsd:choice>
			<xsd:element name="image" type="tImageFile" />
			<xsd:element name="imageref" type="tImageRef" />
		</xsd:choice>
	</xsd:group>
	
	<xsd:complexType name="tStep">
		<xsd:sequence>
			<xsd:group ref="gImage" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="file" type="xsd:string" use="optional" />
		<xsd:attribute name="name" type="xsd:string" use="optional" />
		<xsd:attribute name="duration" type="xsd:integer" use="optional" default="0" />
		<xsd:attribute name="xShift" type="xsd:double" use="optional" />
		<xsd:attribute name="yShift" type="xsd:double" use="optional" />
		<xsd:attribute name="shadow" type="xsd:string" use="optional" />
		<xsd:attribute name="shadowXShift" type="xsd:double" use="optional" />
		<xsd:attribute name="shadowYShift" type="xsd:double" use="optional" />
		<xsd:attribute name="boundYShift" type="tBasePosition" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tDirectionGesture">
		<xsd:sequence>
			<xsd:element name="step" type="tStep" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="tDirection" use="required" />
		<xsd:attribute name="folder" type="xsd:string" use="optional" />
		<xsd:attribute name="xShift" type="xsd:double" use="optional" />
		<xsd:attribute name="yShift" type="xsd:double" use="optional" />
		<xsd:attribute name="shadow" type="xsd:string" use="optional" />
		<xsd:attribute name="shadowXShift" type="xsd:double" use="optional" />
		<xsd:attribute name="shadowYShift" type="xsd:double" use="optional" />
		<xsd:attribute name="boundYShift" type="tBasePosition" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tGesture">
			<xsd:sequence>
				<xsd:element name="direction" type="tDirectionGesture" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="name" type="tGestureName" use="required" />
			<xsd:attribute name="folder" type="xsd:string" use="optional" />
			<xsd:attribute name="repeat" type="xsd:boolean" use="optional" default="false" />
			<xsd:attribute name="proportional" type="xsd:boolean" use="optional" default="false" />			
			<xsd:attribute name="xShift" type="xsd:double" use="optional" />
			<xsd:attribute name="yShift" type="xsd:double" use="optional" />
			<xsd:attribute name="shadow" type="xsd:string" use="optional" />
			<xsd:attribute name="shadowXShift" type="xsd:double" use="optional" />
			<xsd:attribute name="shadowYShift" type="xsd:double" use="optional" />
			<xsd:attribute name="boundYShift" type="tBasePosition" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tGestures">
		<xsd:sequence>
			<xsd:element name="gesture" type="tGesture" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="folder" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tShadow">
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="file" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tShadows">
		<xsd:sequence>
			<xsd:element name="shadow" type="tShadow" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="folder" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tImage">
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="file" type="xsd:string" use="required" />
		<xsd:attribute name="folder" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tImages">
		<xsd:sequence>
			<xsd:element name="image" type="tImage" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="folder" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="tAnimes">
		<xsd:sequence>
			<xsd:element name="colors" type="tColors" minOccurs="0" />
			<xsd:element name="shadows" type="tShadows" minOccurs="0" />
			<xsd:element name="images" type="tImages" minOccurs="0" />
			<xsd:element name="gestures" type="tGestures" />
		</xsd:sequence>
		<xsd:attribute name="scale" type="xsd:integer" use="optional" default="1" />
		<xsd:attribute name="boundHeight" type="xsd:double" use="optional" default="0" />
		<xsd:attribute name="preview" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:element name="animes" type="tAnimes" />

</xsd:schema>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/totalboumboum/fires/penetration/inside/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../schemas/animes.xsd" 
		scale="4" >
<!-- 
	Total Boum Boum
	Copyright 2008-2012 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->

	<gestures>
		<gesture name="BURNING" >
			<direction name="DOWN" folder="down">
				<step duration="50" file="1.png" />
				<step duration="60" file="2.png" />
				<step duration="80" file="3.png" />
				<step duration="80" file="4.png" />
				<step duration="100" file="5.png" />
				<step duration="80" file="4.png" />
				<step duration="80" file="3.png" />
				<step duration="60" file="2.png" />
				<step duration="50" file="1.png" />
			</direction>
			<direction name="LEFT" folder="left">
				<step duration="50" file="1.png" />
				<step duration="60" file="2.png" />
				<step duration="80" file="3.png" />
				<step duration="80" file="4.png" />
				<step duration="100" file="5.png" />
				<step duration="80" file="4.png" />
				<step duration="80" file="3.png" />
				<step duration="60" file="2.png" />
				<step duration="50" file="1.png" />
			</direction>
			<direction name="NONE" folder="none">
				<step duration="50" file="1.png" />
				<step duration="60" file="2.png" />
				<step duration="80" file="3.png" />
				<step duration="80" file="4.png" />
				<step duration="100" file="5.png" />
				<step duration="80" file="4.png" />
				<step duration="80" file="3.png" />
				<step duration="60" file="2.png" />
				<step duration="50" file="1.png" />
			</direction>
			<direction name="RIGHT" folder="right">
				<step duration="50" file="1.png" />
				<step duration="60" file="2.png" />
				<step duration="80" file="3.png" />
				<step duration="80" file="4.png" />
				<step duration="100" file="5.png" />
				<step duration="80" file="4.png" />
				<step duration="80" file="3.png" />
				<step duration="60" file="2.png" />
				<step duration="50" file="1.png" />
			</direction>
			<direction name="UP" folder="up">
				<step duration="50" file="1.png" />
				<step duration="60" file="2.png" />
				<step duration="80" file="3.png" />
				<step duration="80" file="4.png" />
				<step duration="100" file="5.png" />
				<step duration="80" file="4.png" />
				<step duration="80" file="3.png" />
				<step duration="60" file="2.png" />
				<step duration="50" file="1.png" />
			</direction>
		</gesture>
	</gestures>		
</animes>

=== vlabatut/totalboumboum/resources/instances/totalboumboum/bombs/timeremotepenetration/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/animes.xsd" 
		scale="4" >
<!-- 
	Total Boum Boum
	Copyright 2008-2014 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
		
	<colors >
		<colorsprite name="NONE" folder="none" />
		
		<colorsprite name="BLACK" folder="black" />
		<colorsprite name="BLUE" folder="blue" />
		<colorsprite name="BROWN" folder="brown" />
		<colorsprite name="CYAN" folder="cyan" />
		<colorsprite name="GRASS" folder="grass" />
		<colorsprite name="GREEN" folder="green" />
		<colorsprite name="GREY" folder="grey" />
		<colorsprite name="INDIGO" folder="indigo" />
		<colorsprite name="ORANGE" folder="orange" />
		<colorsprite name="PINK" folder="pink" />
		<colorsprite name="PURPLE" folder="purple" />
		<colorsprite name="RED" folder="red" />
		<colorsprite name="RUST" folder="rust" />
		<colorsprite name="ULTRAMARINE" folder="ultramarine" />
		<colorsprite name="WHITE" folder="white" />
		<colorsprite name="YELLOW" folder="yellow" />
	</colors>
	
	<gestures >
		<gesture name="BOUNCING" folder="standing" repeat="true" shadowYShift="-3">
			<direction name="NONE">
				<step duration="240" file="01.png" shadow="large" />
				<step duration="240" file="02.png" shadow="medium" />
				<step duration="240" file="11.png" shadow="small" />
				<step duration="240" file="02.png" shadow="medium" />
			</direction>
		</gesture>
		
		<gesture name="LANDING" folder="standing" repeat="false" >
			<direction name="NONE">
				<step duration="240" file="01.png" shadow="large" />
				<step duration="240" file="02.png" shadow="medium" />
				<step duration="240" file="11.png" shadow="small" />
				<step duration="240" file="02.png" shadow="medium" />
			</direction>
		</gesture>
		
		<gesture name="OSCILLATING" folder="standing" repeat="false" >
			<direction name="DOWN">
				<step duration="240" file="01.png" shadow="large" yShift="5" />
				<step duration="240" file="02.png" shadow="medium" yShift="-5" />
				<step duration="240" file="03.png" shadow="small" yShift="5" />
				<step duration="240" file="04.png" shadow="medium" yShift="-5" />
				<step duration="240" file="05.png" shadow="large" yShift="5" />
				<step duration="240" file="06.png" shadow="medium" yShift="-5" />
				<step duration="240" file="07.png" shadow="small" yShift="5" />
				<step duration="240" file="08.png" shadow="medium" yShift="-5" />
				<step duration="240" file="09.png" shadow="large" yShift="5" />
				<step duration="240" file="10.png" shadow="medium" yShift="-5" />
			</direction>
			<direction name="LEFT">
				<step duration="240" file="01.png" shadow="large" xShift="-5" />
				<step duration="240" file="02.png" shadow="medium" xShift="5" />
				<step duration="240" file="03.png" shadow="small" xShift="-5" />
				<step duration="240" file="04.png" shadow="medium" xShift="5" />
				<step duration="240" file="05.png" shadow="large" xShift="-5" />
				<step duration="240" file="06.png" shadow="medium" xShift="5" />
				<step duration="240" file="07.png" shadow="small" xShift="-5" />
				<step duration="240" file="08.png" shadow="medium" xShift="5" />
				<step duration="240" file="09.png" shadow="large" xShift="-5" />
				<step duration="240" file="10.png" shadow="medium" xShift="5" />
			</direction>
			<direction name="RIGHT">
				<step duration="240" file="01.png" shadow="large" xShift="5" />
				<step duration="240" file="02.png" shadow="medium" xShift="-5" />
				<step duration="240" file="03.png" shadow="small" xShift="5" />
				<step duration="240" file="04.png" shadow="medium" xShift="-5" />
				<step duration="240" file="05.png" shadow="large" xShift="5" />
				<step duration="240" file="06.png" shadow="medium" xShift="-5" />
				<step duration="240" file="07.png" shadow="small" xShift="5" />
				<step duration="240" file="08.png" shadow="medium" xShift="-5" />
				<step duration="240" file="09.png" shadow="large" xShift="5" />
				<step duration="240" file="10.png" shadow="medium" xShift="-5" />
			</direction>
			<direction name="UP">
				<step duration="240" file="01.png" shadow="large" yShift="-5" />
				<step duration="240" file="02.png" shadow="medium" yShift="5" />
				<step duration="240" file="03.png" shadow="small" yShift="-5" />
				<step duration="240" file="04.png" shadow="medium" yShift="5" />
				<step duration="240" file="05.png" shadow="large" yShift="-5" />
				<step duration="240" file="06.png" shadow="medium" yShift="5" />
				<step duration="240" file="07.png" shadow="small" yShift="-5" />
				<step duration="240" file="08.png" shadow="medium" yShift="5" />
				<step duration="240" file="09.png" shadow="large" yShift="-5" />
				<step duration="240" file="10.png" shadow="medium" yShift="5" />
			</direction>
		</gesture>

		<gesture name="OSCILLATING_FAILING" folder="failing" repeat="true" >
			<direction name="DOWN">
				<step duration="240" file="1.png" shadow="large" yShift="-5" />
				<step duration="240" file="2.png" shadow="large" yShift="5" />
				<step duration="240" file="3.png" shadow="large" yShift="-5" />
				<step duration="240" file="2.png" shadow="large" yShift="5" />
			</direction>
			<direction name="LEFT">
				<step duration="240" file="1.png" shadow="large" xShift="-5" />
				<step duration="240" file="2.png" shadow="large" xShift="5" />
				<step duration="240" file="3.png" shadow="large" xShift="-5" />
				<step duration="240" file="2.png" shadow="large" xShift="5" />
			</direction>
			<direction name="RIGHT">
				<step duration="240" file="1.png" shadow="large" xShift="-5" />
				<step duration="240" file="2.png" shadow="large" xShift="5" />
				<step duration="240" file="3.png" shadow="large" xShift="-5" />
				<step duration="240" file="2.png" shadow="large" xShift="5" />
			</direction>
			<direction name="UP">
				<step duration="240" file="1.png" shadow="large" yShift="-5" />
				<step duration="240" file="2.png" shadow="large" yShift="5" />
				<step duration="240" file="3.png" shadow="large" yShift="-5" />
				<step duration="240" file="2.png" shadow="large" yShift="5" />
			</direction>
		</gesture>

		<gesture name="PUNCHED" folder="standing" repeat="true" >
			<direction name="NONE">
				<step duration="240" file="01.png" shadow="large" />
				<step duration="240" file="02.png" shadow="medium" />
				<step duration="240" file="11.png" shadow="small" />
				<step duration="240" file="02.png" shadow="medium" />
			</direction>
		</gesture>
		
		<gesture name="SLIDING" folder="standing" repeat="false" proportional="true">
			<direction name="NONE">
				<step duration="240" file="01.png" shadow="large" />
				<step duration="240" file="02.png" shadow="medium" />
				<step duration="240" file="03.png" shadow="small" />
				<step duration="240" file="04.png" shadow="medium" />
				<step duration="240" file="05.png" shadow="large" />
				<step duration="240" file="06.png" shadow="medium" />
				<step duration="240" file="07.png" shadow="small" />
				<step duration="240" file="08.png" shadow="medium" />
				<step duration="240" file="09.png" shadow="large" />
				<step duration="240" file="10.png" shadow="medium" />
			</direction>
		</gesture>
		
		<gesture name="SLIDING_FAILING" folder="failing" repeat="true">
			<direction name="NONE">
				<step duration="240" file="1.png" shadow="large" />
				<step duration="240" file="2.png" shadow="large" />
				<step duration="240" file="3.png" shadow="large" />
				<step duration="240" file="2.png" shadow="large" />
			</direction>
		</gesture>
		
		<gesture name="STANDING" folder="standing" repeat="false" proportional="true">
			<direction name="NONE">
				<step duration="240" file="01.png" shadow="large" />
				<step duration="240" file="02.png" shadow="medium" />
				<step duration="240" file="03.png" shadow="small" />
				<step duration="240" file="04.png" shadow="medium" />
				<step duration="240" file="05.png" shadow="large" />
				<step duration="240" file="06.png" shadow="medium" />
				<step duration="240" file="07.png" shadow="small" />
				<step duration="240" file="08.png" shadow="medium" />
				<step duration="240" file="09.png" shadow="large" />
				<step duration="240" file="10.png" shadow="medium" />
			</direction>
		</gesture>
		
		<gesture name="STANDING_FAILING" folder="failing" repeat="true" >
			<direction name="NONE">
				<step duration="240" file="1.png" shadow="large" />
				<step duration="240" file="2.png" shadow="large" />
				<step duration="240" file="3.png" shadow="large" />
				<step duration="240" file="2.png" shadow="large" />
			</direction>
		</gesture>		
	</gestures>		
</animes>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/totalboumboum/themes/standard/blocks/softwalls/regular/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../../../schemas/animes.xsd" 
		scale="4" >
<!-- 
	Total Boum Boum
	Copyright 2008-2012 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
	
	<gestures>
		<gesture name="APPEARING" folder="appearing" proportional="true">
			<direction name="NONE">
				<step duration="75" file="1.png" />
				<step duration="75" file="2.png" />
				<step duration="75" file="3.png" />
				<step duration="100" file="4.png" shadow="shadow2" shadowYShift="1.4" />
				<step duration="100" file="5.png" shadow="shadow3" shadowYShift="1.9" />
			</direction>
		</gesture>

		<gesture name="BURNING" folder="burning">
			<direction name="NONE">
				<step duration="150" file="1.png" />
				<step duration="100" file="2.png" />
				<step duration="200" file="3.png" />
				<step duration="75" name="burning4" />
				<step duration="75" name="burning5" />
				<step duration="75" name="burning6" />
				<step duration="75" name="burning7" />
				<step duration="75" name="burning8" />
			</direction>
		</gesture>

		<gesture name="STANDING" folder="standing" shadow="shadow4" shadowYShift="3.4">
			<direction name="NONE">
				<step file="0.png" />
			</direction>
		</gesture>
	</gestures>
</animes>

=== vlabatut/totalboumboum/tags/1.beta.017/TBB/resources/instances/totalboumboum/items/__common/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/animes.xsd" 
		scale="8" >

	<images >
		<image name="smoke1" file="1.png" folder="smoke"/>
		<image name="smoke2" file="2.png" folder="smoke"/>
		<image name="smoke3" file="3.png" folder="smoke"/>
		<image name="smoke4" file="4.png" folder="smoke"/>		
	</images>

	<gestures>

		<gesture name="BURNING" repeat="false" folder="burning">
			<direction name="NONE">
				<step duration="400" file="1.png" />
				<step duration="200" file="2.png" />
				<step duration="150" file="3.png" />
				<step duration="125" file="4.png" />
			</direction>
		</gesture>
		
	</gestures>		
</animes>

=== vlabatut/totalboumboum/TBB/resources/instances/superbomberman1/themes/jump/softwall/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="..\..\..\..\..\xml\schemas\animes.xsd" 
		scale="1" default="standing">
	<shadows>
		<shadow name="standShadow" file="shadow.png" />
	</shadows>
	<gestures>
		<gesture name="standing" folder="standing" repeat="true" shadow="standShadow" shadowYShift="3">
			<direction name="none">
				<step duration="800" file="1.gif" />
				<step duration="50" file="2.gif" />
				<step duration="50" file="3.gif" />
				<step duration="50" file="4.gif" />
				<step duration="800" file="5.gif" />
				<step duration="200" file="4.gif" />
				<step duration="200" file="3.gif" />
				<step duration="200" file="2.gif" />
				<step duration="800" file="1.gif" />
				<step duration="50" file="6.gif" />
				<step duration="50" file="7.gif" />
				<step duration="50" file="8.gif" />
				<step duration="800" file="9.gif" />
				<step duration="200" file="8.gif" />
				<step duration="200" file="7.gif" />
				<step duration="200" file="6.gif" />
			</direction>
		</gesture>
		<gesture name="burning" folder="burning">
			<direction name="none">
				<step duration="150" file="1.gif" />
				<step duration="75" file="2.gif" />
				<step duration="75" file="3.gif" />
				<step duration="75" file="4.gif" />
				<step duration="75" file="5.gif" />
				<step duration="75" file="6.gif" />
			</direction>
		</gesture>
	</gestures>
</animes>

=== vlabatut/totalboumboum/tags/1.beta.025/TBB/resources/instances/superbomberman1/themes/circles/blocks/softwalls/retractable/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../../../schemas/animes.xsd" 
		scale="1" >
<!-- 
	Total Boum Boum
	Copyright 2008-2013 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
		
	<gestures>
		<gesture name="BOUNCING" shadow="fallShadow" shadowYShift="-7">
			<direction name="NONE">
				<step name="standing" />
			</direction>
		</gesture>

		<gesture name="LANDING" shadow="standShadow" shadowYShift="3">
			<direction name="NONE">
				<step name="standing" />
			</direction>
		</gesture>
		
		<gesture name="STANDING" repeat="true" >
			<direction name="NONE">
				<step duration="1600" name="appearing4" shadow="shadow" shadowYShift="4"/>
				<step duration="100" name="appearing3"/>
				<step duration="50" name="appearing2"/>
				<step duration="50" name="appearing1"/>
				<step duration="650" />
				<step duration="50" name="appearing1"/>
				<step duration="50" name="appearing2"/>
				<step duration="100" name="appearing3"/>
			</direction>
		</gesture>
	</gestures>
</animes>

=== vlabatut/totalboumboum/tags/1.beta.020/TBB/restmp/instances/superbomberman5/themes/urbanzone/mushroom/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../schemas/animes.xsd" 
		scale="1" default="standing">
	<gestures>
		
		<gesture name="burning" folder="burning" repeat="false" >
			<direction name="none">
				<step duration="150" file="1.gif" />
				<step duration="75" file="2.gif" />
				<step duration="75" file="3.gif" />
				<step duration="75" file="4.gif" />
				<step duration="75" file="5.gif" />
				<step duration="75" file="6.gif" />
			</direction>
		</gesture>
		
		<gesture name="hiding" >
			<direction name="none">
				<step />
			</direction>
		</gesture>
		
		<gesture name="spawning" folder="spawning" repeat="false" >
			<direction name="none">
				<step duration="150" file="1.gif" shadow="shadow1.png" shadowYShift="1" />
				<step duration="100" file="2.gif" shadow="shadow2.png" shadowYShift="1" />
				<step duration="100" file="3.gif" shadow="shadow3.png" shadowYShift="1" />
				<step duration="100" file="4.gif" shadow="shadow4.png" shadowYShift="2" />
			</direction>
		</gesture>
		
		<gesture name="standing" folder="standing" repeat="false" shadow="shadow.png" shadowYShift="2">
			<direction name="none">
				<step file="standing.gif" />
			</direction>
		</gesture>
		
	</gestures>
</animes>

=== vlabatut/totalboumboum/TBB/resources/instances/superbomberman1/themes/jump/blocks/softwall/animes/animes.xml
<?xml version="1.0" encoding="utf-8"?>
<animes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../../schemas/animes.xsd" 
		scale="1" >

	<shadows>
		<shadow name="standShadow" file="shadow.png" />
	</shadows>

	<gestures>
		<gesture name="APPEARING" folder="appearing" proportional="true">
			<direction name="NONE">
				<step duration="150" file="1.gif" />
				<step duration="75" file="2.gif" />
				<step duration="75" file="3.gif" />
				<step duration="75" file="4.gif" />
				<step duration="75" file="5.gif" />
				<step duration="75" file="6.gif" />
			</direction>
		</gesture>

		<gesture name="BURNING" folder="burning">
			<direction name="NONE">
				<step duration="150" file="1.gif" />
				<step duration="75" file="2.gif" />
				<step duration="75" file="3.gif" />
				<step duration="75" file="4.gif" />
				<step duration="75" file="5.gif" />
				<step duration="75" file="6.gif" />
			</direction>
		</gesture>

		<gesture name="STANDING" folder="standing" repeat="true" shadow="standShadow" shadowYShift="2">
			<direction name="NONE">
				<step duration="800" file="1.gif" />
				<step duration="50" file="2.gif" />
				<step duration="50" file="3.gif" />
				<step duration="50" file="4.gif" />
				<step duration="800" file="5.gif" />
				<step duration="200" file="4.gif" />
				<step duration="200" file="3.gif" />
				<step duration="200" file="2.gif" />
				<step duration="800" file="1.gif" />
				<step duration="50" file="6.gif" />
				<step duration="50" file="7.gif" />
				<step duration="50" file="8.gif" />
				<step duration="800" file="9.gif" />
				<step duration="200" file="8.gif" />
				<step duration="200" file="7.gif" />
				<step duration="200" file="6.gif" />
			</direction>
		</gesture>
	</gestures>
</animes>
