=== vlabatut/totalboumboum/TBB/resources/schemas/blockset.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="_ability.xsd"/>

<!-- 
	Total Boum Boum
	Copyright 2008-2014 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
-->

	<xsd:complexType name="tBlock">
		<xsd:attribute name="folder" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="tGroupName">
		<xsd:restriction base="xsd:string">
			<!-- anything but the string "defaulg" (or an uppercase/lowercase variant) -->
			<xsd:pattern value="([^Dd]|[Dd][^Ee]|[Dd][Ee][^Ff]|[Dd][Ee][Ff][^Aa]|[Dd][Ee][Ff][Aa][^Uu]|[Dd][Ee][Ff][Aa][Uu][^Ll]|[Dd][Ee][Ff][Aa][Uu][Ll][^Tt]|[^Dd][^Ee][^Ff][^Aa][^Uu][^Ll][^Tt]).*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="tGroup">
		<xsd:sequence>
			<xsd:element name="block" type="tBlock" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="tGroupName" use="required" />
		<xsd:attribute name="folder" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tBlocks">
		<xsd:sequence>
			<xsd:choice maxOccurs="unbounded" >
				<xsd:element name="block" type="tBlock" minOccurs="0" />
				<xsd:element name="group" type="tGroup" minOccurs="0" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tBlockset">
		<xsd:sequence>
			<xsd:element name="abstractBlocks" type="tBlocks" minOccurs="0"/>
			<xsd:element name="concreteBlocks" type="tBlocks" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="blockset" type="tBlockset" />

</xsd:schema>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/superbomberman1/themes/jump/blocks/blockset.xml
<?xml version="1.0" encoding="utf-8"?>
<blockset 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/blockset.xsd" >
<!-- 
	Total Boum Boum
	Copyright 2008-2012 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
	
	<abstractBlocks >
		<block name="common" folder="_common" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="common_hard" folder="_common"/>
		</group>
	</abstractBlocks>
	
	<concreteBlocks>
		<block folder="softwall" name="softwall" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="regular" folder="regular"/>
			
			<block name="insidedown" folder="insidedown"/>
			<block name="insidedownleft" folder="insidedownleft"/>
			<block name="insidedownright" folder="insidedownright"/>
			<block name="insideleft" folder="insideleft"/>
			<block name="insideleftup" folder="insideleftup"/>
			<block name="insideright" folder="insideright"/>
			<block name="insiderightup" folder="insiderightup"/>
			<block name="insideup" folder="insideup"/>
			<block name="insideupleft" folder="insideupleft"/>
			<block name="insideupright" folder="insideupright"/>
			<block name="outsideleftA" folder="outsideleftA"/>
			<block name="outsideleftB" folder="outsideleftB"/>
			<block name="outsideleftC" folder="outsideleftC"/>
			<block name="outsideleftD" folder="outsideleftD"/>
			<block name="outsideleftE" folder="outsideleftE"/>
			<block name="outsideleftF" folder="outsideleftF"/>
			<block name="outsideleftG" folder="outsideleftG"/>
			<block name="outsideleftH" folder="outsideleftH"/>
			<block name="outsideleftI" folder="outsideleftI"/>
			<block name="outsiderightA" folder="outsiderightA"/>
			<block name="outsiderightB" folder="outsiderightB"/>
			<block name="outsiderightC" folder="outsiderightC"/>
			<block name="outsiderightD" folder="outsiderightD"/>
			<block name="outsiderightE" folder="outsiderightE"/>
			<block name="outsiderightF" folder="outsiderightF"/>
			<block name="outsiderightG" folder="outsiderightG"/>
			<block name="outsiderightH" folder="outsiderightH"/>
			<block name="outsiderightI" folder="outsiderightI"/>
			<block name="outsidevertical" folder="outsidevertical"/>
		</group>
	</concreteBlocks>
	
</blockset>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/superbomberman1/themes/tunnel/blocks/blockset.xml
<?xml version="1.0" encoding="utf-8"?>
<blockset 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/blockset.xsd" >
	
	<abstractBlocks >
		<block name="common" folder="_common" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="common_hard" folder="_common"/>
		</group>

		<group name="tunnels" folder="tunnels">
			<block name="common_tunnel" folder="_common"/>
		</group>
	</abstractBlocks>
	
	<concreteBlocks>
		<block folder="softwall" name="softwall" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="regular" folder="regular"/>
			
			<block name="center" folder="center"/>
			<block name="down" folder="down"/>
			<block name="downleft" folder="downleft"/>
			<block name="downright" folder="downright"/>
			<block name="downT" folder="downT"/>
			<block name="horizontalA" folder="horizontalA"/>
			<block name="horizontalB" folder="horizontalB"/>
			<block name="leftT" folder="leftT"/>
			<block name="rightT" folder="rightT"/>
			<block name="up" folder="up"/>
			<block name="upleft" folder="upleft"/>
			<block name="upright" folder="upright"/>
			<block name="upT" folder="upT"/>
		</group>

		<group name="tunnels" folder="tunnels">
			<block name="center" folder="center"/>
			<block name="down" folder="down"/>
			<block name="downT" folder="downT"/>
			<block name="horizontal" folder="horizontal"/>
			<block name="left" folder="left"/>
			<block name="leftT" folder="leftT"/>
			<block name="right" folder="right"/>
			<block name="rightT" folder="rightT"/>
			<block name="up" folder="up"/>
			<block name="upT" folder="upT"/>
			<block name="vertical" folder="vertical"/>
		</group>
	</concreteBlocks>
	
</blockset>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/superbomberman1/themes/western/blocks/blockset.xml
<?xml version="1.0" encoding="utf-8"?>
<blockset 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/blockset.xsd" >
	
	<abstractBlocks >
		<block name="common" folder="_common" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="common_hard" folder="_common"/>
		</group>
	</abstractBlocks>
	
	<concreteBlocks>
		<block folder="softwall" name="softwall" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="regular" folder="regular"/>
			
			<block name="insidedown" folder="insidedown"/>
			<block name="insidedownleft" folder="insidedownleft"/>
			<block name="insidedownright" folder="insidedownright"/>
			<block name="insideleft" folder="insideleft"/>
			<block name="insideleftdown" folder="insideleftdown"/>
			<block name="insideleftup" folder="insideleftup"/>
			<block name="insideright" folder="insideright"/>
			<block name="insiderightdown" folder="insiderightdown"/>
			<block name="insiderightup" folder="insiderightup"/>
			<block name="insideup" folder="insideup"/>
			<block name="insideupleft" folder="insideupleft"/>
			<block name="insideupright" folder="insideupright"/>
			<block name="outsidedownleft" folder="outsidedownleft"/>
			<block name="outsidedownright" folder="outsidedownright"/>
			<block name="outsideleft" folder="outsideleft"/>
			<block name="outsideleftdown" folder="outsideleftdown"/>
			<block name="outsideright" folder="outsideright"/>
			<block name="outsiderightdown" folder="outsiderightdown"/>
			<block name="outsideupleft" folder="outsideupleft"/>
			<block name="outsideupright" folder="outsideupright"/>
		</group>
	</concreteBlocks>
	
</blockset>

=== vlabatut/totalboumboum/TBB/resources/instances/superbomberman1/themes/tournament5/blocks/blockset.xml
<?xml version="1.0" encoding="utf-8"?>
<blockset 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../schemas/blockset.xsd" >
	
	<abstractBlocks >
		<block name="common" folder="_common" />
		
		<group name="hardwalls" folder="hardwalls">
			<block name="common_hard" folder="_common"/>
		</group>

		<group name="softwalls" folder="softwalls">
			<block name="common_soft" folder="_common"/>
		</group>
	</abstractBlocks>
	
	<concreteBlocks>
		<group name="softwalls" folder="softwalls">
			<block name="redyellow" folder="redyellow" />
			<block name="yellowred" folder="yellowred" />
		</group>	
		
		<group name="hardwalls" folder="hardwalls">
			<block name="regular" folder="regular"/>
			
		</group>
	</concreteBlocks>
	
</blockset>
