=== vlabatut/totalboumboum/TBB/resources/schemas/controls.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- 
	Total Boum Boum
	Copyright 2008-2013 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
-->

	<xsd:complexType name="tOnOff">
		<xsd:attribute name="key" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tEvent">
		<xsd:sequence>
			<xsd:element name="on" type="tOnOff" minOccurs="0" />
			<xsd:element name="off" type="tOnOff" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="autofire" type="xsd:boolean" default="false" />
	</xsd:complexType>

	<xsd:complexType name="tControls">
		<xsd:sequence>
			<xsd:element name="event" type="tEvent" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="controls" type="tControls" />

</xsd:schema>

=== vlabatut/totalboumboum/TBB/resources/settings/controls/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<controls xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\resources\schemas\controls.xsd">
	<event name="DROPBOMB" autofire="true">
		<on key="VK_P" />
		<off key="VK_P" />
	</event>
	<event name="PUNCHBOMB" autofire="false">
		<on key="VK_DOLLAR" />
		<off key="VK_DOLLAR" />
	</event>
	<event name="RIGHT" autofire="true">
		<on key="VK_ASTERISK" />
		<off key="VK_ASTERISK" />
	</event>
	<event name="DOWN" autofire="true">
		<on key="VK_UNDEFINED" />
		<off key="VK_UNDEFINED" />
	</event>
	<event name="UP" autofire="true">
		<on key="VK_DEAD_CIRCUMFLEX" />
		<off key="VK_DEAD_CIRCUMFLEX" />
	</event>
	<event name="LEFT" autofire="true">
		<on key="VK_M" />
		<off key="VK_M" />
	</event>
	<event name="TRIGGERBOMB" autofire="false">
		<on key="VK_COLON" />
		<off key="VK_COLON" />
	</event>
</controls>
