=== vlabatut/totalboumboum/tags/1.beta.016/TBB/resources/schemas/players.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="tLocation">
		<xsd:attribute name="player" type="xsd:integer" use="required" />
		<xsd:attribute name="col" type="xsd:integer" use="required" />
		<xsd:attribute name="line" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tCase">
		<xsd:sequence>
			<xsd:element name="location" type="tLocation" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="players" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tLocations">
		<xsd:sequence>
			<xsd:element name="case" type="tCase"  maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tItem">
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="number" type="xsd:integer" use="optional"  default="1"/>
	</xsd:complexType>

	<xsd:complexType name="tItems">
		<xsd:sequence>
			<xsd:element name="item" type="tItem"  maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tPlayers">
		<xsd:sequence>
			<xsd:element name="locations" type="tLocations" />
			<xsd:element name="items" type="tItems" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="players" type="tPlayers" />

</xsd:schema>

=== vlabatut/totalboumboum/TBB/resources/levels/tournament201112/classic/players.xml
<?xml version="1.0" encoding="UTF-8"?>
<players xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\resources\schemas\players.xsd">
	<locations>
		<case players="2">
			<location player="00" line="01" col="02" />
			<location player="01" line="13" col="14" />
		</case>
		<case players="3">
			<location player="00" line="01" col="02" />
			<location player="01" line="01" col="14" />
			<location player="02" line="13" col="02" />
		</case>
		<case players="4">
			<location player="00" line="01" col="02" />
			<location player="01" line="01" col="14" />
			<location player="02" line="13" col="02" />
			<location player="03" line="13" col="14" />
		</case>
		<case players="5">
			<location player="00" line="01" col="02" />
			<location player="01" line="01" col="14" />
			<location player="02" line="13" col="02" />
			<location player="03" line="13" col="14" />
			<location player="04" line="07" col="08" />
		</case>
	</locations>
	<items>
		<item name="extrabomb" number="2" />
		<item name="extraflame" number="2" />
	</items>
</players>

=== vlabatut/totalboumboum/TBB/resources/levels/nbm1Custom/classic/players.xml
<?xml version="1.0" encoding="utf-8"?>
<players 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../schemas/players.xsd" >
<!-- 
	Total Boum Boum
	Copyright 2008-2012 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->
	
	<locations>
		<case players="1">
			<location player="0" line="1" col="2" />
		</case>
		<case players="2">
			<location player="0" line="1" col="2" />
			<location player="1" line="11" col="14" />
		</case>
		<case players="3">
			<location player="0" line="1" col="2" />
			<location player="1" line="1" col="14" />
			<location player="2" line="11" col="2" />
		</case>
		<case players="4">
			<location player="0" line="1" col="2" />
			<location player="1" line="1" col="14" />
			<location player="2" line="11" col="2" />
			<location player="3" line="11" col="14" />
		</case>
	</locations>
	
	<items>
		<item name="extrabomb" number="2" />
		<item name="extraflame" number="3" />
	</items>
	
</players>
