=== vlabatut/totalboumboum/tags/1.beta.025/TBB/resources/schemas/gesture_modulations.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:include schemaLocation="_ability.xsd"/>

<!-- 
	Total Boum Boum
	Copyright 2008-2013 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
-->

	<xsd:complexType name="tModulation">
		<xsd:attribute name="frame" type="xsd:boolean" use="optional" default="false" />
		<xsd:attribute name="strength" type="xsd:string" use="optional" default="0" />
	</xsd:complexType>

	<xsd:complexType name="tExtendedModulation">
		<xsd:complexContent>
			<xsd:extension base="tModulation">
				<xsd:attribute name="contact" type="tContactList" use="optional" default="ANY" />
				<xsd:attribute name="tilePosition" type="tTilePositionList" use="optional" default="ANY" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tSelfModulation">
		<xsd:complexContent>
			<xsd:extension base="tModulation">
				<xsd:sequence>
					<xsd:element name="name" type="tAbilityName" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tOtherModulation">
		<xsd:complexContent>
			<xsd:extension base="tExtendedModulation">
				<xsd:sequence>
					<xsd:element name="name" type="tAbilityName" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tRestrictions">
		<xsd:sequence>
			<xsd:element name="ability" type="tAbility" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tActorModulation">
		<xsd:complexContent>
			<xsd:extension base="tModulation">
				<xsd:sequence>
					<xsd:element name="action" type="tActionActor" />
					<xsd:element name="actorRestrictions" type="tRestrictions" minOccurs="0" />
					<xsd:element name="targetRestrictions" type="tRestrictions" minOccurs="0" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tTargetModulation">
		<xsd:complexContent>
			<xsd:extension base="tModulation">
				<xsd:sequence>
					<xsd:element name="action" type="tActionTarget" />
					<xsd:element name="actorRestrictions" type="tRestrictions" minOccurs="0" />
					<xsd:element name="targetRestrictions" type="tRestrictions" minOccurs="0" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tCircumstances">
		<xsd:attribute name="contact" type="tContactList" use="optional" default="ANY" />
		<xsd:attribute name="tilePosition" type="tTilePositionList" use="optional" default="ANY" />
		<xsd:attribute name="orientation" type="tOrientationList" use="optional" default="ANY" />
	</xsd:complexType>

	<xsd:complexType name="tThirdModulation">
		<xsd:complexContent>
			<xsd:extension base="tExtendedModulation">
				<xsd:sequence>
					<xsd:element name="action" type="tActionThird" />
					<xsd:element name="actorRestrictions" type="tRestrictions" minOccurs="0" />
					<xsd:element name="targetRestrictions" type="tRestrictions" minOccurs="0" />
					<xsd:element name="actorCircumstances" type="tCircumstances" />
					<xsd:element name="targetCircumstances" type="tCircumstances" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="tSelfModulations">
		<xsd:sequence>
			<xsd:element name="modulation" type="tSelfModulation" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tOtherModulations">
		<xsd:sequence>
			<xsd:element name="modulation" type="tOtherModulation" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tActorModulations">
		<xsd:sequence>
			<xsd:element name="modulation" type="tActorModulation" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tTargetModulations">
		<xsd:sequence>
			<xsd:element name="modulation" type="tTargetModulation" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tThirdModulations">
		<xsd:sequence>
			<xsd:element name="modulation" type="tThirdModulation" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tGestureModulations">
		<xsd:sequence>
			<xsd:element name="selfModulations" type="tSelfModulations" />
			<xsd:element name="otherModulations" type="tOtherModulations" />
			<xsd:element name="actorModulations" type="tActorModulations" />
			<xsd:element name="targetModulations" type="tTargetModulations" />
			<xsd:element name="thirdModulations" type="tThirdModulations" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="gesture-modulations" type="tGestureModulations" />

</xsd:schema>

=== vlabatut/totalboumboum/trunk/TBB/resources/instances/superbomberman1/themes/flower/blocks/softwalls/spawn/modulations/hiding.xml
<?xml version="1.0" encoding="utf-8"?>
<gesture-modulations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../../../schemas/gesture_modulations.xsd" >

	<selfModulations>
	</selfModulations>
	
	<otherModulations>
	</otherModulations>
	
	<actorModulations>
	</actorModulations>
	
	<targetModulations>
<!--  	CONSUME --> 
		<modulation frame="true" strength="0" >
			<action name="CONSUME" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
		</modulation>
	</targetModulations>
	
	<thirdModulations>
	</thirdModulations>

</gesture-modulations>

=== vlabatut/totalboumboum/resources/instances/superbomberman1/themes/_common/regular_hardwall/modulations/appearing.xml
<?xml version="1.0" encoding="utf-8"?>
<gesture-modulations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../../../../schemas/gesture_modulations.xsd" >
<!-- 
	Total Boum Boum
	Copyright 2008-2014 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
 -->

	<selfModulations>
	</selfModulations>
	
	<otherModulations>
	</otherModulations>
	
	<actorModulations>
	</actorModulations>
	
	<targetModulations>
<!--  	CONSUME --> 
		<modulation frame="true" strength="0" >
			<action name="CONSUME" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
		</modulation>
	</targetModulations>
	
	<thirdModulations>
<!--  	APPEAR --> 
		<modulation frame="false" strength="0" >
			<action name="APPEAR" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions>
				<ability strength="2"><name value="SPRITE_TRAVERSE_WALL" /></ability>
			</actorRestrictions>
			<targetRestrictions />
			<actorCircumstances contact="ANY" tilePosition="ANY" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
		<modulation frame="true" strength="0" >
			<action name="APPEAR" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="ANY" tilePosition="ANY" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
<!--  	CONSUME --> 
		<!-- prevent fire from consuming anything located under the block -->
		<modulation frame="true" strength="0" >
			<action name="CONSUME" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="FIRE" target="ANY" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances />
			<targetCircumstances />
		</modulation>
<!--  	LAND --> 
		<modulation frame="false" strength="0" >
			<action name="LAND" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions>
				<ability strength="2"><name value="SPRITE_TRAVERSE_WALL" /></ability>
			</actorRestrictions>
			<targetRestrictions />
			<actorCircumstances contact="ANY" tilePosition="ANY" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
		<modulation frame="true" strength="0" >
			<action name="LAND" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="ANY" tilePosition="ANY" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
<!--  	MOVELOW --> 
		<!-- ability to go through walls -> not an obstacle -->
		<modulation frame="false" strength="0" >
			<action name="MOVELOW" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions>
				<ability strength="2"><name value="SPRITE_TRAVERSE_WALL" /></ability>
			</actorRestrictions>
			<targetRestrictions />
			<actorCircumstances contact="ANY" tilePosition="ANY" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
		<!-- intersection, same tile -> not an obstacle -->
		<modulation frame="false" strength="0" >
			<action name="MOVELOW" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="INTERSECTION" tilePosition="SAME" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
		<!-- intersection, different tile, same orientation -> obstacle -->
		<modulation frame="true" strength="0" >
			<action name="MOVELOW" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="INTERSECTION" tilePosition="NEIGHBOR" orientation="FACE" />
			<targetCircumstances  />
		</modulation>
		<!-- intersection, different tile, different orientation -> not an obstacle -->
		<modulation frame="false" strength="0" >
			<action name="MOVELOW" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="INTERSECTION" tilePosition="NEIGHBOR" orientation="BACK NEUTRAL OTHER" />
			<targetCircumstances  />
		</modulation>
		<!-- other -> obstacle -->
		<modulation frame="true" strength="0" >
			<action name="MOVELOW" direction="ANY" contact="ANY"
				tilePosition="ANY" orientation="ANY" actor="SOME" />
			<actorRestrictions />
			<targetRestrictions />
			<actorCircumstances contact="COLLISION INTERSECTION" tilePosition="NEIGHBOR SAME" orientation="ANY" />
			<targetCircumstances  />
		</modulation>
	</thirdModulations>

</gesture-modulations>
