=== vlabatut/totalboumboum/tags/1.beta.025/TBB/resources/schemas/level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- 
	Total Boum Boum
	Copyright 2008-2013 Vincent Labatut 
	
	This file is part of Total Boum Boum.
	
	Total Boum Boum is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.
	
	Total Boum Boum is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Total Boum Boum.  If not, see <http://www.gnu.org/licenses/>.
-->

	<xsd:complexType name="tTitle">
		<xsd:attribute name="value" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tAuthor">
		<xsd:attribute name="value" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tSource">
		<xsd:attribute name="value" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tPreview">
		<xsd:attribute name="file" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tDisplay">
		<xsd:attribute name="forceAll" type="xsd:boolean" use="required" />
		<xsd:attribute name="maximize" type="xsd:boolean" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tGlobalDimension">
		<xsd:attribute name="height" type="xsd:integer" use="required" />
		<xsd:attribute name="width" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tVisibleDimension">
		<xsd:attribute name="height" type="xsd:integer" use="required" />
		<xsd:attribute name="width" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tVisiblePosition">
		<xsd:attribute name="leftCol" type="xsd:integer" use="required" />
		<xsd:attribute name="upLine" type="xsd:integer" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tTheme">
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tInstance">
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="tLevel">
		<xsd:sequence>
			<xsd:element name="title" type="tTitle" />
			<xsd:element name="author" type="tAuthor" />
			<xsd:element name="source" type="tSource" />
			<xsd:element name="preview" type="tPreview" />
			
			<xsd:element name="instance" type="tInstance" />
			<xsd:element name="theme" type="tTheme" />
			<xsd:element name="globalDimension" type="tGlobalDimension" />
			<xsd:element name="visibleDimension" type="tVisibleDimension" />
			<xsd:element name="visiblePosition" type="tVisiblePosition" />
			<xsd:element name="display" type="tDisplay" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="level" type="tLevel" />

</xsd:schema>

=== vlabatut/totalboumboum/TBB/resources/levels/tournament201011/bombfest/level.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\resources\schemas\level.xsd">
	<title value="Bombfest" />
	<author value="Vincent Labatut" />
	<source value="original" />
	<preview file="preview.jpg" />
	<instance name="tournament" />
	<theme name="tournament4" />
	<globalDimension height="15" width="15" />
	<visibleDimension height="15" width="15" />
	<visiblePosition upLine="0" leftCol="0" />
	<display forceAll="false" maximize="true" />
</level>

=== vlabatut/totalboumboum/trunk/TBB/resources/levels/tests201011/kesimalvarol_itsatrap/level.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../resources/schemas/level.xsd">
	<title value="It's a trap!" />
	<author value="Ali Baran Kesimal / Işıl Varol" />
	<source value="original" />
	<preview file="preview.jpg" />
	<instance name="superbomberman1" />
	<theme name="tournament4" />
	<globalDimension height="8" width="8" />
	<visibleDimension height="8" width="8" />
	<visiblePosition upLine="0" leftCol="0" />
	<display forceAll="false" maximize="true" />
</level>

=== vlabatut/totalboumboum/trunk/TBB/resources/levels/tournament201112/qualif4/level.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\resources\schemas\level.xsd">
	<title value="Qualif'4" />
	<author value="Vincent Labatut" />
	<source value="Original" />
	<preview file="preview.jpg" />
	<instance name="superbomberman1" />
	<theme name="tournament5" />
	<globalDimension height="9" width="22" />
	<visibleDimension height="7" width="22" />
	<visiblePosition upLine="1" leftCol="0" />
	<display forceAll="false" maximize="true" />
</level>

=== vlabatut/totalboumboum/TBB/resources/levels/temp/level/level.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\..\resources\schemas\level.xsd">
	<title value="New level" />
	<author value="Vincent Labatut" />
	<source value="original" />
	<preview file="preview.jpg" />
	<instance name="superbomberman1" />
	<theme name="normal" />
	<globalDimension height="15" width="21" />
	<visibleDimension height="15" width="21" />
	<visiblePosition upLine="0" leftCol="0" />
	<display forceAll="true" maximize="true" />
</level>

=== vlabatut/totalboumboum/tags/beta.016/TBB/resources/levels/sbm1Official/battle_03/level.xml
<?xml version="1.0" encoding="utf-8"?>
<level 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../../../schemas/level.xsd" >

	<title value="Battle Zone #3" />
	<author value="Vincent Labatut" />
	<source value="Super Bomberman 1" />
	<preview file="preview.jpg" />

	<instance name="superbomberman1" />
	<theme name="bomb"/>

	<globalDimension height="13" width="17" />
	<visibleDimension height="13" width="15" />
	<visiblePosition upLine="0" leftCol="1" />
	<display forceAll="false" maximize="true" />
		
</level>
